# -*- coding: utf-8 -*-
"""MODULO1 - PRODUCAO HOPITALAR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1pNLS9v5VR1a7geU_To09qb48DmLs-j

#ANALISANDO DADOS DOS HOSPITAIS DO BRASIL
"""

import pandas as pd
df = pd.read_csv('/content/assets/Processamento.csv',encoding='ISO-8859-1',sep=';',skiprows=3 ,skipfooter=12 , thousands= '.', decimal= ',')

"""df = pd.read_csv(**'caminho do csv'**,** tipo de codificador **,sep=' **Separador**',skiprows= **pular linhas iniciais** ,skipfooter= **Pular linhas finais**)

**.Head()** imprime os 5 primeiros elementos do meu dataframe  *lembrar de Cabeca*
"""

df.head()

"""**.Tail()** imprime os 5 ultimos elementos do meu dataframe      *lembrar de cauda*


"""

df.tail()

df.mean(numeric_only=True)

df.info()

pd.options.display.float_format = '{:,.2f}'.format

df.mean(numeric_only=True)

ultima_coluna = len(df)-2
df_ultima_coluna = df.iloc[ultima_coluna]
df_ultima_coluna

df[df.columns[-1]].mean(numeric_only=True)